export const SET_USER = 'SET_USER';
export const SET_POSTS = 'SET_POSTS';
export const SET_CURRENT_SCENARIO = 'SET_CURRENT_SCENARIO';
export const SET_CURRENT_SCENARIO_VALUE = 'SET_CURRENT_SCENARIO_VALUE';
